"""Unified entry point for TER experiments."""
from __future__ import annotations

import argparse
import random
import yaml
import numpy as np
import torch
import torch.nn as nn
import yaml


PROJECT_ROOT = Path(__file__).resolve().parent


def project_path(path: str | Path) -> Path:
    path = Path(path)
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def config_path_from_arg(path_arg: str) -> Path:
    path = Path(path_arg)
    if path.exists():
        return path.resolve()

    fallback = project_path(path)
    if fallback.exists():
        return fallback

    raise FileNotFoundError(f"Config not found: {path_arg}")


def get_device() -> str:
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True


def require_ttt_artifacts(paths: dict[str, Path]) -> None:
    missing = [f"{label}: {path}" for label, path in paths.items() if not path.exists()]
    if not missing:
        return

    missing_text = "\n".join(f"- {item}" for item in missing)
    raise FileNotFoundError(
        "TTT requires SSL artifacts generated by the self_supervised task first.\n"
        f"Missing:\n{missing_text}\n"
        "Run: python run.py --task self_supervised --config configs/self_supervised.yaml"
    )


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run TER experiments")
    parser.add_argument(
        "--task",
        choices=["test_time_training", "self_supervised", "ttt", "ssl"],
        required=True,
    )
    parser.add_argument("--config", required=True)
    args = parser.parse_args()

    config_path = config_path_from_arg(args.config)
    cfg = yaml.safe_load(config_path.read_text(encoding="utf-8"))

    seed = int(cfg.get("seed", 42))
    set_seed(seed)

    task = args.task
    if task == "ttt":
        task = "test_time_training"
    elif task == "ssl":
        task = "self_supervised"

    cfg = yaml.safe_load(config_path.read_text())
    set_seed(cfg.get("seed", 42))
    device = "mps" if torch.backends.mps.is_available() else "cpu"
    print(f"[TASK] {task} | [DEVICE] {device}")

    if task == "self_supervised":
        from src.datasets import build_cifar10_loaders, build_simclr_loader
        from src.self_supervised import SSLConfig, SelfSupervisedTrainer

        dataset_cfg = cfg["dataset"]
        model_cfg = cfg.get("model", {})
        training_cfg = cfg["training"]
        log_cfg = cfg.get("logging", {})

        ssl_cfg = SSLConfig(
            method=training_cfg["method"],
            epochs=training_cfg["epochs"],
            batch_size=training_cfg["batch_size"],
            lr=training_cfg["lr"],
            projection_dim=model_cfg.get("embedding_dim", 128),
            backbone=model_cfg.get("backbone", "resnet18"),
            linear_eval_epochs=training_cfg.get("linear_eval_epochs", 30),
        )

        trainer = SelfSupervisedTrainer(ssl_cfg, device=device)

        simclr_loader = build_simclr_loader(
            root=dataset_cfg["root"],
            batch_size=training_cfg["batch_size"],
            num_workers=dataset_cfg.get("num_workers", 2),
            download=dataset_cfg.get("download", False),
            max_samples=dataset_cfg.get("max_simclr_samples", dataset_cfg.get("max_train_samples")),
        )

        train_loader, val_loader = build_cifar10_loaders(
            root=dataset_cfg["root"],
            batch_size=training_cfg["batch_size"],
            num_workers=dataset_cfg.get("num_workers", 2),
            download=dataset_cfg.get("download", False),
            max_train_samples=dataset_cfg.get("max_train_samples"),
            max_test_samples=dataset_cfg.get("max_test_samples"),
        )

        trainer.pretrain(simclr_loader) # 2 vues augmentées
        clf, _ = trainer.linear_eval(train_loader, val_loader) # évaluation linéaire sur les features brutes
        clf_path = log_cfg.get("classifier_path", "results/self_supervised/classifier.pt")
        Path(clf_path).parent.mkdir(parents=True, exist_ok=True)
        torch.save(clf.state_dict(), clf_path)
        print(f"[SSL] Classifier linéaire sauvegardé dans {clf_path}")
        

        # sauvegardes
        if log_cfg.get("save_backbone"):
            Path(log_cfg["backbone_path"]).parent.mkdir(parents=True, exist_ok=True)
            trainer.save_backbone(log_cfg["backbone_path"])

        stats_cfg = cfg.get("source_stats", {})
        if stats_cfg.get("compute", True):
            source_stats_path = project_path(stats_cfg.get("save_path", "results/self_supervised/source_stats.pt"))
            source_stats_path.parent.mkdir(parents=True, exist_ok=True)
            trainer.compute_and_save_source_stats(val_loader, source_stats_path)

    elif task == "test_time_training":
        from src.datasets import build_cifar10c_loader, missing_cifar10c_files
        from src.metrics import evaluate_ttt

        dataset_cfg = cfg["dataset"]
        model_cfg = cfg["model"]
        adaptation_cfg = cfg["adaptation"]

        # charger backbone 
        from src.self_supervised import SimCLRModel, SSLConfig
        ssl_cfg = SSLConfig(backbone=model_cfg.get("backbone", "resnet18"))
        simclr = SimCLRModel(ssl_cfg)
        ckpt = model_cfg.get("checkpoint")
        if ckpt and Path(ckpt).exists():
            simclr.backbone.load_state_dict(torch.load(ckpt, map_location=device))
            print(f"[TTT] Backbone chargé depuis {ckpt}")

        clf = nn.Linear(simclr.feat_dim, model_cfg["num_classes"])
        clf_path = model_cfg.get("classifier_path", "results/self_supervised/classifier.pt")
        if Path(clf_path).exists():
            clf.load_state_dict(torch.load(clf_path, map_location=device))
            print(f"[TTT] Classifier linéaire chargé depuis {clf_path}")

        model = nn.Sequential(simclr.backbone, clf).to(device)

        source_stats = torch.load(adaptation_cfg["source_stats_path"], map_location=device)
        ttt_cfg = TTTConfig(
            lr=adaptation_cfg["lr"],
            steps_per_batch=adaptation_cfg["steps_per_batch"],
            adaptation_task=adaptation_cfg["method"],
        )
        adapter = TTTAdapter(model, ttt_cfg, source_stats)

        # évaluation sur une corruption 
        loader = build_cifar10c_loader(
            root=dataset_cfg["root"],
            corruption=dataset_cfg["corruption"],
            severity=dataset_cfg["severity"],
            batch_size=dataset_cfg["batch_size"],
            num_workers=dataset_cfg.get("num_workers", 2),
            max_samples=dataset_cfg.get("max_samples"),
        )

        print(f"\n{'Corruption':<22} {'Baseline':>10} {'TTT':>10} {'Gain':>10}")
        print("-" * 58)
        for corruption in corruptions:
            corruption_fallback_used = bool(missing_cifar10c_files(data_root, [corruption]))
            loader = build_cifar10c_loader(
                root=str(data_root),
                corruption=corruption,
                severity=severity,
                batch_size=dataset_cfg["batch_size"],
                num_workers=dataset_cfg.get("num_workers", 0),
                allow_synthetic_fallback=allow_synthetic_fallback,
            )
            res_base = evaluate_ttt(adapter, loader, device, use_ttt=False)
            res_ttt = evaluate_ttt(
                adapter,
                loader,
                device,
                use_ttt=True,
                use_safe_ttt=use_safe_ttt,
                max_allowed_confidence_drop=max_allowed_confidence_drop,
            )
            gain = res_ttt["accuracy"] - res_base["accuracy"]
            rows.append(
                {
                    "corruption": corruption,
                    "severity": severity,
                    "baseline_accuracy": res_base["accuracy"],
                    "ttt_accuracy": res_ttt["accuracy"],
                    "gain": gain,
                    "improvement": gain,
                    "baseline_correct": res_base["correct"],
                    "ttt_correct": res_ttt["correct"],
                    "total": res_base["total"],
                    "batch_size": dataset_cfg["batch_size"],
                    "steps_per_batch": ttt_cfg.steps_per_batch,
                    "adaptation_lr": ttt_cfg.lr,
                    "use_safe_ttt": use_safe_ttt,
                    "safe_ttt_rejected_batches": res_ttt["safe_ttt_rejected_batches"],
                    "safe_ttt_total_batches": res_ttt["safe_ttt_total_batches"],
                    "synthetic_fallback_used": corruption_fallback_used,
                }
            )
            sign = "+" if gain >= 0 else ""
            print(
                f"{corruption:<22} {res_base['accuracy']*100:>9.2f}% "
                f"{res_ttt['accuracy']*100:>9.2f}% {sign}{gain*100:>9.2f}%"
            )

        output_dir = project_path(cfg.get("logging", {}).get("output_dir", "results/test_time_training"))
        output_dir.mkdir(parents=True, exist_ok=True)
        results_path = output_dir / "results.csv"
        with results_path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
        print(f"[TTT] Results saved to {results_path}")


if __name__ == "__main__":
    main()
