"""Unified entry point for TER experiments."""
from __future__ import annotations

import argparse
import csv
import random
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import yaml


PROJECT_ROOT = Path(__file__).resolve().parent


def project_path(path: str | Path) -> Path:
    path = Path(path)
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def config_path_from_arg(path_arg: str) -> Path:
    path = Path(path_arg)
    if path.exists():
        return path.resolve()

    fallback = project_path(path)
    if fallback.exists():
        return fallback

    raise FileNotFoundError(f"Config not found: {path_arg}")


def get_device() -> str:
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True


def require_ttt_artifacts(paths: dict[str, Path]) -> None:
    missing = [f"{label}: {path}" for label, path in paths.items() if not path.exists()]
    if not missing:
        return

    missing_text = "\n".join(f"- {item}" for item in missing)
    raise FileNotFoundError(
        "TTT requires SSL artifacts generated by the self_supervised task first.\n"
        f"Missing:\n{missing_text}\n"
        "Run: python run.py --task self_supervised --config configs/self_supervised.yaml"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run TER experiments")
    parser.add_argument(
        "--task",
        choices=["test_time_training", "self_supervised", "ttt", "ssl"],
        required=True,
    )
    parser.add_argument("--config", required=True)
    args = parser.parse_args()

    config_path = config_path_from_arg(args.config)
    cfg = yaml.safe_load(config_path.read_text(encoding="utf-8"))

    seed = int(cfg.get("seed", 42))
    set_seed(seed)

    task = args.task
    if task == "ttt":
        task = "test_time_training"
    elif task == "ssl":
        task = "self_supervised"

    device = get_device()
    print(f"[TASK] {task} | [DEVICE] {device} | [SEED] {seed}")

    if task == "self_supervised":
        from src.datasets import build_cifar10_loaders, build_simclr_loader
        from src.self_supervised import SSLConfig, SelfSupervisedTrainer

        training_cfg = cfg["training"]
        ssl_cfg = SSLConfig(
            method=training_cfg.get("method", "simclr"),
            max_epochs=training_cfg.get("max_epochs", training_cfg.get("epochs", 50)),
            batch_size=training_cfg.get("batch_size", 128),
            lr=training_cfg.get("lr", 3e-4),
            temperature=training_cfg.get("temperature", 0.5),
            projection_dim=cfg.get("model", {}).get("embedding_dim", 128),
            backbone=cfg.get("model", {}).get("backbone", "resnet18"),
            patience=training_cfg.get("patience", 7),
            min_delta=training_cfg.get("min_delta", 1e-3),
        )

        trainer = SelfSupervisedTrainer(ssl_cfg, device=device)

        simclr_loader = build_simclr_loader(
            root=str(project_path(cfg["dataset"]["root"])),
            batch_size=ssl_cfg.batch_size,
            download=cfg["dataset"].get("download", False),
        )

        train_loader, val_loader = build_cifar10_loaders(
            root=str(project_path(cfg["dataset"]["root"])),
            batch_size=ssl_cfg.batch_size,
            download=cfg["dataset"].get("download", False),
        )

        log_cfg = cfg.get("logging", {})
        output_dir = project_path(log_cfg.get("output_dir", "results/self_supervised"))
        output_dir.mkdir(parents=True, exist_ok=True)

        best_backbone_path = project_path(log_cfg.get("best_backbone_path", "results/self_supervised/best_backbone.pt"))
        last_backbone_path = project_path(log_cfg.get("last_backbone_path", "results/self_supervised/last_backbone.pt"))
        log_path = project_path(log_cfg.get("training_log_path", "results/self_supervised/training_log.csv"))

        trainer.pretrain(
            simclr_loader,
            log_path=log_path,
            best_backbone_path=best_backbone_path,
            last_backbone_path=last_backbone_path,
        )

        clf, _ = trainer.linear_eval(train_loader, val_loader)
        clf_path = project_path("results/self_supervised/classifier.pt")
        clf_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(clf.state_dict(), clf_path)
        print(f"[SSL] Linear classifier saved to {clf_path}")

        if log_cfg.get("save_backbone", True):
            legacy_path = project_path(log_cfg.get("backbone_path", "results/self_supervised/simclr_backbone.pt"))
            trainer.save_backbone(legacy_path)

        stats_cfg = cfg.get("source_stats", {})
        if stats_cfg.get("compute", True):
            source_stats_path = project_path(stats_cfg.get("save_path", "results/self_supervised/source_stats.pt"))
            source_stats_path.parent.mkdir(parents=True, exist_ok=True)
            trainer.compute_and_save_source_stats(val_loader, source_stats_path)

    elif task == "test_time_training":
        from src.datasets import build_cifar10c_loader, missing_cifar10c_files
        from src.metrics import evaluate_ttt
        from src.self_supervised import SSLConfig, SimCLRModel
        from src.test_time_training import TTTAdapter, TTTConfig

        ssl_cfg = SSLConfig(backbone=cfg.get("model", {}).get("backbone", "resnet18"))
        simclr = SimCLRModel(ssl_cfg)

        ckpt = cfg["model"].get("checkpoint")
        ckpt_path = project_path(ckpt) if ckpt else None
        clf_path = project_path("results/self_supervised/classifier.pt")
        source_stats_path = project_path(cfg["adaptation"]["source_stats_path"])
        artifact_paths = {
            "backbone": ckpt_path,
            "classifier": clf_path,
            "source stats": source_stats_path,
        }
        require_ttt_artifacts({k: v for k, v in artifact_paths.items() if v is not None})

        if ckpt_path:
            simclr.backbone.load_state_dict(torch.load(ckpt_path, map_location=device))
            print(f"[TTT] Backbone loaded from {ckpt_path}")

        clf = nn.Linear(simclr.feat_dim, cfg["model"]["num_classes"])
        clf.load_state_dict(torch.load(clf_path, map_location=device))
        print(f"[TTT] Linear classifier loaded from {clf_path}")

        model = nn.Sequential(simclr.backbone, clf).to(device)
        source_stats = torch.load(source_stats_path, map_location=device)
        ttt_cfg = TTTConfig(
            lr=cfg["adaptation"]["lr"],
            steps_per_batch=cfg["adaptation"]["steps_per_batch"],
            adaptation_task=cfg["adaptation"].get("method", "actmad"),
        )
        adapter = TTTAdapter(model, ttt_cfg, source_stats)

        dataset_cfg = cfg["dataset"]
        corruptions = dataset_cfg.get("corruptions") or [dataset_cfg["corruption"]]
        severity = dataset_cfg["severity"]
        data_root = project_path(dataset_cfg["root"])
        allow_synthetic_fallback = dataset_cfg.get("allow_synthetic_fallback", True)
        missing_cifar10c = missing_cifar10c_files(data_root, corruptions)
        if missing_cifar10c:
            if not allow_synthetic_fallback:
                missing_text = "\n".join(f"- {path}" for path in missing_cifar10c)
                raise FileNotFoundError(
                    "CIFAR-10-C files are missing.\n"
                    f"Missing:\n{missing_text}\n"
                    "Place the CIFAR-10-C .npy files under data/raw/cifar10c/CIFAR-10-C "
                    "or set allow_synthetic_fallback: true."
                )
            print(
                "[DATA] CIFAR-10-C files not found. "
                "Using locally generated CIFAR-10 test corruptions for this evaluation."
            )
        rows = []

        print(f"\n{'Corruption':<22} {'Baseline':>10} {'TTT':>10} {'Gain':>10}")
        print("-" * 58)
        for corruption in corruptions:
            loader = build_cifar10c_loader(
                root=str(data_root),
                corruption=corruption,
                severity=severity,
                batch_size=dataset_cfg["batch_size"],
                num_workers=dataset_cfg.get("num_workers", 0),
                allow_synthetic_fallback=allow_synthetic_fallback,
            )
            res_base = evaluate_ttt(adapter, loader, device, use_ttt=False)
            res_ttt = evaluate_ttt(adapter, loader, device, use_ttt=True)
            gain = res_ttt["accuracy"] - res_base["accuracy"]
            rows.append(
                {
                    "corruption": corruption,
                    "severity": severity,
                    "baseline_accuracy": res_base["accuracy"],
                    "ttt_accuracy": res_ttt["accuracy"],
                    "improvement": gain,
                    "baseline_correct": res_base["correct"],
                    "ttt_correct": res_ttt["correct"],
                    "total": res_base["total"],
                }
            )
            sign = "+" if gain >= 0 else ""
            print(
                f"{corruption:<22} {res_base['accuracy']*100:>9.2f}% "
                f"{res_ttt['accuracy']*100:>9.2f}% {sign}{gain*100:>9.2f}%"
            )

        output_dir = project_path(cfg.get("logging", {}).get("output_dir", "results/test_time_training"))
        output_dir.mkdir(parents=True, exist_ok=True)
        results_path = output_dir / "results.csv"
        with results_path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
        print(f"[TTT] Results saved to {results_path}")


if __name__ == "__main__":
    main()
