# unified entry point for ter experiments
import argparse
import random
import yaml
import numpy as np
import torch
import torch.nn as nn
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent


def project_path(path: str | Path) -> Path:
    path = Path(path)
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def config_path_from_arg(path_arg: str) -> Path:
    path = Path(path_arg)
    if path.exists():
        return path.resolve()

    fallback = project_path(path)
    if fallback.exists():
        return fallback

    raise FileNotFoundError(f"Config not found: {path_arg}")


def require_ttt_artifacts(paths: dict[str, Path]) -> None:
    missing = [f"{label}: {path}" for label, path in paths.items() if not path.exists()]
    if not missing:
        return

    missing_text = "\n".join(f"- {item}" for item in missing)
    raise FileNotFoundError(
        "TTT requires SSL artifacts generated by the self_supervised task first.\n"
        f"Missing:\n{missing_text}\n"
        "Run this command from Project_final_master1:\n"
        "python run.py --task self_supervised --config configs/self_supervised.yaml"
    )

def get_device() -> str:
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)


def main() -> None:
    # parse cli arguments
    parser = argparse.ArgumentParser(description="Run TER experiments")
    parser.add_argument(
        "--task",
        choices=["test_time_training", "self_supervised", "ttt", "ssl"],
        required=True,
    )
    parser.add_argument("--config", required=True)
    args = parser.parse_args()

    # check config path first
    config_path = config_path_from_arg(args.config)
    
    task = args.task
    if task == "ttt": task = "test_time_training"
    elif task == "ssl": task = "self_supervised"

    cfg = yaml.safe_load(config_path.read_text())
    device = get_device()
    print(f"[TASK] {task} | [DEVICE] {device}")

    # ssl pretraining
    if task == "self_supervised":
        from src.self_supervised import SelfSupervisedTrainer, SSLConfig
        from src.datasets import build_cifar10_loaders, build_simclr_loader

        ssl_cfg = SSLConfig(
            method=cfg["training"]["method"],
            epochs=cfg["training"]["epochs"],
            batch_size=cfg["training"]["batch_size"],
            lr=cfg["training"]["lr"],
        )

        trainer = SelfSupervisedTrainer(ssl_cfg, device=device)

        simclr_loader = build_simclr_loader(
            root=str(project_path(cfg["dataset"]["root"])),
            batch_size=cfg["training"]["batch_size"],
            download=cfg["dataset"].get("download", False),
        )

        train_loader, val_loader = build_cifar10_loaders(
            root=str(project_path(cfg["dataset"]["root"])),
            batch_size=cfg["training"]["batch_size"],
            download=cfg["dataset"].get("download", False),
        )

        trainer.pretrain(simclr_loader) # train with two augmented views
        clf, _ = trainer.linear_eval(train_loader, val_loader) # train the linear head
        log_cfg = cfg.get("logging", {})
        clf_path = project_path(log_cfg.get("classifier_path", "results/self_supervised/classifier.pt"))
        clf_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(clf.state_dict(), clf_path)
        print(f"[SSL] Linear classifier saved to {clf_path}")
        

        # save ssl artifacts
        if log_cfg.get("save_backbone"):
            backbone_path = project_path(log_cfg["backbone_path"])
            backbone_path.parent.mkdir(parents=True, exist_ok=True)
            trainer.save_backbone(str(backbone_path))

        stats_cfg = cfg.get("source_stats", {})
        if stats_cfg.get("compute"):
            source_stats_path = project_path(stats_cfg["save_path"])
            source_stats_path.parent.mkdir(parents=True, exist_ok=True)
            trainer.compute_and_save_source_stats(val_loader, str(source_stats_path))

    # ttt actmad adaptation
    elif task == "test_time_training":
        from src.test_time_training import TTTAdapter, TTTConfig
        from src.datasets import build_cifar10c_loader
        from src.metrics import evaluate_ttt
        import torchvision.models as tvm

        # load the backbone
        from src.self_supervised import SimCLRModel, SSLConfig
        ssl_cfg = SSLConfig()
        simclr = SimCLRModel(ssl_cfg)
        ckpt = cfg["model"].get("checkpoint")
        ckpt_path = project_path(ckpt) if ckpt else None
        clf_path = project_path(cfg["model"].get("classifier_path", "results/self_supervised/classifier.pt"))
        source_stats_path = project_path(cfg["adaptation"]["source_stats_path"])
        artifact_paths = {
            "backbone": ckpt_path,
            "classifier": clf_path,
            "source stats": source_stats_path,
        }
        require_ttt_artifacts({k: v for k, v in artifact_paths.items() if v is not None})

        if ckpt_path:
            simclr.backbone.load_state_dict(torch.load(ckpt_path, map_location=device))
            print(f"[TTT] Backbone loaded from {ckpt_path}")

        clf = nn.Linear(simclr.feat_dim, cfg["model"]["num_classes"])
        clf.load_state_dict(torch.load(clf_path, map_location=device))
        print(f"[TTT] Linear classifier loaded from {clf_path}")

        model = nn.Sequential(simclr.backbone, clf).to(device)

        source_stats = torch.load(source_stats_path, map_location=device)
        ttt_cfg = TTTConfig(
            lr=cfg["adaptation"]["lr"],
            steps_per_batch=cfg["adaptation"]["steps_per_batch"],
            adaptation_task=cfg["adaptation"]["method"],
        )

        adapter = TTTAdapter(model, ttt_cfg, source_stats)

        # evaluate one corruption
        loader = build_cifar10c_loader(
            root=str(project_path(cfg["dataset"]["root"])),
            corruption=cfg["dataset"]["corruption"],
            severity=cfg["dataset"]["severity"],
            batch_size=cfg["dataset"]["batch_size"],
        )

        print("\n--- Baseline (without TTT) ---")
        res_base = evaluate_ttt(adapter, loader, device, use_ttt=False)
        print(f"Accuracy: {res_base['accuracy']*100:.2f}%")

        print("\n--- ActMAD TTT ---")
        res_ttt = evaluate_ttt(adapter, loader, device, use_ttt=True)
        print(f"TTT accuracy: {res_ttt['accuracy']*100:.2f}%")
        print(f"Improvement: {(res_ttt['accuracy'] - res_base['accuracy'])*100:.2f}%")

if __name__ == "__main__":
    main()
